### PR TITLE
Use multiple adjectives

### PR DESCRIPTION
**Pull request by brandinchiu**
added ability to optionally choose how many adjectives to use to generate the string to increase output complexity.

### CODE REVIEW

**Comment by claudiodekker** [comment]
Hey @brandinchiu 👋,

Thanks for your pull request!

Unfortunately, I'm going to delay merging this code for now. To preserve my ability to adequately maintain the library, I need to be very careful regarding the amount and kind of code/features I include.

While I don't usually go into detail about my reasons for rejecting a PR, let me explain:
- While this code supports multiple adjectives, it arbitrarily limits it to 10, without a "real" reason to. If the user wants to have even 200, duplicate or not, why would we want to prevent this?
- More importantly: While this code does add functionality, I believe that the additional code that needs to be maintained as a result adding of this functionality, does not weigh up to the limited use-cases, especially given how simple it would be to implement this in your own code (perhaps not as simple as adding a "times" flag, but still):

```php
use ClaudioDekker\WordGenerator\Generator;
use ClaudioDekker\WordGenerator\Words\Noun;
use Illuminate\Support\Collection;

Collection::make(array_fill(0, 9, null))
  ->map(fn () => Noun::random())
  ->prepend(Generator::generate("-"))
  ->join("-")
```

If possible, do consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by brandinchiu** [comment]
I appreciate the explanation, and support the decision.

**Comment by claudiodekker** [comment]
Hey @brandinchiu,

This came up again as part of https://github.com/claudiodekker/word-generator/pull/8, and since that implementation was very minimal, I've just merged and released it as part of [v1.4.0](https://github.com/claudiodekker/word-generator/releases/tag/v1.4.0). I figured I'd let you know about this, since this is something you had an use-case for, too.

Thanks again for initially suggesting this feature, and by extension, putting weight behind the decision to get this feature added! 👍

**Comment by brandinchiu** [comment]
I appreciate the heads up! Happy to lend a voice.

**Pull request closed without merging**
